name: Test

on:
  push:
    paths:
      - '**.py'
      - '**.yml'
      - 'requirements-dev.lock'
    branches:
      - main
      - neodb
  pull_request:
    paths:
      - '**.py'
      - 'requirements-dev.lock'

jobs:
  test:
    name: test py${{ matrix.python-version }} with pg${{ matrix.postgres-version }}
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    timeout-minutes: 8
    strategy:
      matrix:
        python-version: ["3.12"]
        postgres-version: [12, 16]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Set up Postgres ${{ matrix.postgres-version }}
        uses: ankane/setup-postgres@v1
        with:
          postgres-version: ${{ matrix.postgres-version }}
          database: takahe
      - name: Install dependencies
        run: |
          sudo apt-get install -y libwebp-dev libjpeg-dev
          python -m pip install -r requirements-dev.lock
      - name: Run pytest
        env:
          TAKAHE_DATABASE_SERVER: "postgres://localhost/takahe"
        run: |
          python -m pytest
      - name: Run pre-commit
        run: |
          pre-commit run -a --show-diff-on-failure
